name: owwn_coding_challenge
description: OWWN Coding Challenge.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  equatable: ^2.0.3
  bloc_test: ^9.0.3
  go_router: ^4.0.1
  flutter_secure_storage: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true
